apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-configmap
data:
  DB_SERVICE: 'postgres-svc.default'
  FLASK_APP: 'project/__init__.py'
  FLASK_ENV: 'development'
  CLEAN_DB: 'true'
  NATS_URI: 'nats://nats:4222'
