apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-configmap
data:
  DB_SERVICE: 'postgres-svc.default'
  RABBITMQ_URI: 'tcp://rabbitmq-svc:5672'
  FLASK_APP: 'project/__init__.py'
  FLASK_ENV: 'development'
  CLEAN_DB: 'true'
