apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres-secret.yaml
- postgres.yaml
- rabbitmq.yaml
- flask-app-configmap.yaml
- flask-app-secret.yaml
- flask-app.yaml
- react-app.yaml
- ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: xzarem/flask-app
  newTag: 475daf39099f2d69f1cedc875a69085c96250f3c
- name: IMAGE_PLACEHOLDER_REACT
  newName: xzarem/react-app
  newTag: 475daf39099f2d69f1cedc875a69085c96250f3c
