apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres-secret.yaml
- postgres.yaml
- rabbitmq.yaml
- flask-app-configmap.yaml
- flask-app-secret.yaml
- flask-app.yaml
- react-app.yaml
- ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: xzarem/flask-app
  newTag: 53727892ca98773bcd983499861a6c0e6848a3b5
- name: IMAGE_PLACEHOLDER_REACT
  newName: xzarem/frontend-app
  newTag: 53727892ca98773bcd983499861a6c0e6848a3b5
