apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres-secret.yaml
- postgres.yaml
- rabbitmq.yaml
- flask-app-configmap.yaml
- flask-app-secret.yaml
- flask-app.yaml
- react-app.yaml
- ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: xzarem/flask-app
  newTag: e62cf2a23be181ca4a7822f8375aa1ebb1ed9d0c
- name: IMAGE_PLACEHOLDER_REACT
  newName: xzarem/react-app
  newTag: e62cf2a23be181ca4a7822f8375aa1ebb1ed9d0c
