apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres-secret.yaml
- sealed-secret-async-broadcaster.yaml
- postgres.yaml
- nats.yaml
- async-broadcaster.yaml
- flask-app-configmap.yaml
- flask-app-secret.yaml
- flask-app.yaml
- react-app.yaml
- ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: xzarem/flask-app
  newTag: v2
- name: IMAGE_PLACEHOLDER_REACT
  newName: xzarem/frontend-app
  newTag: f9e4590f9fb9b19af2fa942536fb1ebef10eec63
- name: IMAGE_PLACEHOLDER_BROADCASTER
  newName: xzarem/async-broadcaster
  newTag: d9f13b258004dbff02d26e5f83997235df940a35206ddf80d061b3e8dae055dc
