apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- postgres-secret.yaml
- sealed-secret-async-broadcaster.yaml
- postgres.yaml
- nats.yaml
- async-broadcaster.yaml
- flask-app-configmap.yaml
- flask-app-secret.yaml
- flask-app.yaml
- react-app.yaml
- ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: xzarem/flask-app
  newTag: 5136666c5171ff4ee8ef12fa60e6b393a7b094ad
- name: IMAGE_PLACEHOLDER_BROADCASTER
  newName: xzarem/async-broadcaster
  newTag: latest
- name: IMAGE_PLACEHOLDER_REACT
  newName: xzarem/frontend-app
  newTag: 5136666c5171ff4ee8ef12fa60e6b393a7b094ad
