apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: cG9zdGdyZXNkYg==
  POSTGRES_USER: YWRtaW4=
  # echo -n 'password' | base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ=