apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: broadcaster-secret
  namespace: default
spec:
  encryptedData:
    CHAT_ID: AgCs1FZ+5bRik40jPkg0ktqnHfATfVHn3Do0/nnxnNZ3l/rkjPmeaPQ3S6+twxMdQcEo8WuWqM74bKA50VAC1G3EjTFZ4uwcIrKtrFtJZMIh+0Fvxh3ukOSZQBsJvuOT/G7VfBPN0f47Lxu1Df5b/PZ2n1ie15niGfbPzaGMYdKMGgH4KAkqKSKw48N9vTydbfKscc5DKgi1Zo5PXztHoEqvf+NjxoOrE+OKE4Gyd5QY6Wj8dzs/U54Y9Oxl6jwURKtZGVd7dnBlmdagTJWG1sW+DSLjGGQR/EWxMHWOxX5NW5fgzoMV6XrFwGJ7aZxdYkbkBkhorKxNMdvucFizg0fJyAnx6WDla70mbMEALd29HzN8QqFxeOrgUNarV+oEOrBGn3j6LquzdQg/FWbogEyzdtx7ATkDLvqZRLvWnw7bkBeofUAtW/cvtyXYwNzUoHo+SzVAkVa7H5Q0IFwtfjnS+knbbfVRsGC7yetq05ZR+xDjLujJ5KILarPMmf/GKizTW84HwJ6yIH8Ih6e1XoSAlsxWKJF7nI93OKB1NEZz+yUUZtXjnd/2W10yT/HBfXbmb0UDmVedcaqIc3gQv4xdXo7uSLAqojzsHI+lWMsU8JOvqlv+DWsZ4R8pyajA9DrbjldYYmEAnVc4XfUrpaWg45j62v8ETpuAUQDpvjB3peh7/K7ChhH7hMbxAqa7ajbhdZInrZuGRB+N
    TELEGRAM_TOKEN: AgBENBWx0M7w49EQ0eZvRDJZtvQyKx8v/ICn2XwThBBxk8MPolPqpeJsqvYrZFPIVTXyZT5dBTAZ3eiz3sa+K07VzrC5GDGaLeVXd/gwosLzV7aLHX9S+fGujTNB/1/N0p1DPMAupt/LdrBqgMDYalt1D1JFJucbW5lPpwcyJviBp4pjiw96kTobAdZEpKA5t4FeZ7RwHmge5UGn6YlxKAyt9fNpjt6VeAyAe1VJnvuBT0WET/iceTxpZ0UxhxFnFzKK5v1CIQqP9J/tNszUlZR64fxlEF5pQq26ICQ9fum5541bTnTso71aUClWEA8ArJkMk3DMBwLzUIayEuIOE9xgSEtIikYKkqhfGQJMRE1R5F/kqhZmnapuFGu2DxahwJf3qOUdMs6RGudBx6IDuUPat4/ChZt9IVwz9fKjWxb9JRdbB8cN+DPeY4G1HsYb/IVqxrd+whwubxfT2tSyy7HSGqOUAJ8clhV+Nqf4t8GgsM+Uu06co0lIR5MxRWP0zwERnC9daQ3SrG4ljFYGJL2pqONf8uKI+NLHxz9re1a14DiRdxh4WqxkNKu/V1GejOUW0EgOUmAlqM+Cj8bLipftdgnxdn8PIB5bKzDr1QN50eb8kdUyg/HDMIoRHOAIpRfsyoecyzNL+loXa73ueekEaD3QwzcMKC6xct65h1XyTVnXhYW6NH2Wetw9nio829gTqtEaOUSL61/hC+OE5G7iwq92QUhwtGZ4YYZbPEzAnGaAVPzSKIYY1SA1oePa
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: broadcaster-secret
      namespace: default
    type: Opaque

