apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: xzarem/dwk-4-gitops-app
  newTag: e6ae39c00165398e74c4c6d76e31b0688efd659e
