version: '3.8'

services:

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on: 
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment: 
      - REACT_APP_BACKEND_BASE_URL=http://localhost:5000/todo
    depends_on: 
      - backend

  backend:
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    ports:
      - 5000:5000
    env_file:
      - ./backend-app/.env.dev
    depends_on:
      - db

  broadcaster:
    build:
      context: ./broadcaster
      dockerfile: Dockerfile
    command: python broadcaster.py
    env_file:
      - ./broadcaster/.env.dev
    depends_on:
      - rabbitmq
      
  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flask_db

volumes:
  postgres_data: