name: Build and push the latest build to staging

on:
  push:
    branches: [ master ]

jobs:
  build_push_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login, build and push to ACR
        uses: docker/login-action@v1.8.0
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build . -t ${{ secrets.ACR_NAME }}/demo-project:latest -f project/Dockerfile
          docker push ${{ secrets.ACR_NAME }}/demo-project:latest
